language: java

env:
  global:
    - VERIFY_USE_PUBLIC_BINARIES=true
  # CODACY_PROJECT_TOKEN
    - secure: "lQ0rlJwFtLRbk8aAexwXLKZUp6LNuC9TGhHUsYD92WGTT03QDTGDbpbpQXStLEPthMzbrX1qPp+GmcTqRKHgSISP6LAXOeAuI6AZtuc0NKzLd/425JiaksytDv0m4rfuozRveUyZRMq/geqTRvtEuRiW6qDKRT8l0emtkT2olM584gTp2fJZw9k6TgTPebrj70N9Ec7T3DSYBqaFnNduHHRBVlbqmrnGF6tfMGQZ0rcOZFiMYpIuwaX9b5+rfTR5ZjbuWzyjK0MQdfH8stFGSiAYcwu3+Wfp7w416SnwQh/J2plFcA8I2pKZ9Gl63eQBGeGAyh+4fqYZz7XiqFkoaBCKOyHDHtPeqdbNZCU0fgzbfdCBjULUiI51ItF1SFDg21WxxS3gJBkh1wBMU14CvYpcQOwe5rKc1emdfuRndmTrpheOehXjdF3eYfQlqAnIeyzMlpYf3PzNWJojjSLy0be/Q97pA6S44+RVWVJEz57BiEV+Hxy9rp9S/JFR2TSCCHEF7g9flGeX6ImTcz274eKtRAIU2Tx9MqbBcDkY/CfevrO1usaV6qQ4uheZxhjxzj5WkZ/p21+r2GZNHffgQylYlIqiG4ZJHlFBU4fpdD+Tb6y/sPyjMJdgIxMU1q4YSu5nux21LQ3bmKp7WvcJx+NzfQmQ2E4QSW21LvYrOpA="
  # GITHUB_PAT
    - secure: "Dsn7MKMlv02wwErdmmiZm0C9d0kRu9dJmvtoj0P0egi2EO7p6hWK6/mjYT+8kqnHq8k1TAJusdNJKYSYtbPdkGT93S9Ka9/cgpYs5qJZDSvXhVs08Pxc4DTdZWR8zzbLr0qNal110s2xmdFPNUbBTss6w9E2uHUJXtIlqFJGJCG0esjni/jldAw7w/Nilvv+8D71sADFCoelF7FbkRexa6+EnodT+aU4KL4/c+F+tPLc3ZtadTMVqT+0ly2uStkRvTByOTgxT0pOGY09MS6jop5ru8kXQCHI8VxhZEGh0e+neWFgO99y6hP9KhaHTk3ZVFhdSDZfsRjTDIn+/ajgRGHb0uIA+SQUoUWvjQNPfDiedKTptU6Qn1U0Iax/81YQIRwBCHTDwS15iZKKeDKzctlwdgj+y60Jr+IU0yQLFDzI4hBbpIYBfHhp8MJmLvtRouBM+KmKHa3oBROlXYOiExM7r7SG2HetLeLzL3uPBu2fef/ZcpP6Dsn+3BCTRq4oM6w7D5naMN8P08Ii7YvWPU/PAVyhbfY61/tncmJdDNiFkLbEueTd3/5M4XbqhUNFWdH5DUjJ/625QkUPy+XriQXwNsQrjyKqfP+Euct/IIIzx0iwhpV/hqDLv9kLSTnk0xeB8wwj4PVu4TP+p3kVFiUykHCNW2wPkzy9dE0ZqdU="

jdk:
  - openjdk11

before_install:
  - sudo apt-get install jq
  - curl -u ida-codacy-bot:$GITHUB_PAT -LSs $(curl -u ida-codacy-bot:$GITHUB_PAT -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar

install:
  - npm install -g snyk@1.146.0

script:
  - ./gradlew --no-daemon test
  - snyk/test.sh
  - libs/check-dependencies.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_success:
  - snyk/monitor.sh
  - ./gradlew jacocoRootReport
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
